### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by konne** [Snowflake-Labs/sqltools-snowflake-driver#47]
Hi can you please attach the vsix also to the releases and or upload them also to Open VSX.
Otherwise it is not allow to use in non VSCode products. See:
https://www.gitpod.io/docs/vscode-extensions

bye

**Comment by fredrikhgrelland** [comment]
I came here from a gitpod.io workspace. SQLTools is published on opencsx, but your driver was missing. Any chance you could publish it to openvsx as well? https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by seenickels** [comment]
bumping this as well, please!

**Comment by koszti** [comment]
hey, the latest 0.4.2 version is now available on ovsx at https://open-vsx.org/extension/koszti/snowflake-driver-for-sqltools.
Open VSX is currently showing a warning that it was published by a non-verified published. Following the [OVSX docs](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace) I sent a PR to the ovsx maintainers : https://github.com/EclipseFdn/open-vsx.org/issues/1216 . Once this issue got resolved, the warning should go away.


From now on every new release will be published automatically to Visual Studio Marketplace and Open VSX (https://github.com/Snowflake-Labs/sqltools-snowflake-driver/pull/54 will take care about it)

Can you please confirm if you can install it via gitpod so I can close this issue?

**Comment by koszti** [comment]
it’s now completely available on open vsx
