### ISSUE TITLE
Connection to host's all DB's is not supported

### ISSUE THREAD

**Issue by Shir-Ariel-Havron-Hunters** [Snowflake-Labs/sqltools-snowflake-driver#51]
Hi! Thank you for a very useful extension! :)
I would like to be able to connect to a host and use all of it's DB's simultaneously.
This is possible with other sql-agents, such as DataGrip (e.i. like in the picture 
![Screen Shot 2021-12-30 at 15 12 08](https://user-images.githubusercontent.com/96186495/147755162-53d898eb-1840-4236-8125-e166ce59433f.png) 
), however in the extension it is mandatory to choose a single DB to connect to, and then the connection does not include other DB's on the same host (
![Screen Shot 2021-12-30 at 15 15 40](https://user-images.githubusercontent.com/96186495/147755266-e4b1ea9e-6c07-4e86-9bc9-c1668f8ae267.png)
). 

Would that be possible? 
Thank you very much!

**Comment by adamNewell** [comment]
@Shir-Ariel-Havron-Hunters the most recent release (0.5.0) should help you out here. Let me know what you think!

**Comment by koszti** [comment]
closing it because it's implemented in 0.5.0
